Repository board-together/BE-Board-Together, pull requests merged in 2023-02, with the labels that each got.

#3 Bk/setup
  .github/pull_request_template.md
  .gitignore
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/puma.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: enhancement

#8 Add schema image and update README to include schema
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  public/Screenshot 2023-02-02 at 2.58.15 PM.png
Labels: documentation

#20 Bk/update readme
  Gemfile
  README.md
  app/models/game.rb
  app/models/user_game.rb
  app/services/game_service.rb
  public/Schema 2-5-23.png
  public/Schema 2-6-23.png
  spec/factories/game.rb
  spec/factories/user.rb
  spec/factories/user_game.rb
  spec/rails_helper.rb
  spec/services/game_service_spec.rb
Labels: documentation

#33 Create user
  .rubocop.yml
  app/graphql/board_together_schema.rb
  app/graphql/mutations/base_mutation.rb
  app/graphql/mutations/create_user.rb
  app/graphql/types/game_type.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/user_game_type.rb
  app/graphql/types/user_type.rb
  app/models/user.rb
  spec/graphql/mutations/create_user_spec.rb
  spec/graphql/queries/games/search_games_spec.rb
  spec/rails_helper.rb
Labels: enhancement

#37 Refactor factorybot settings and formatter run
  Gemfile
  config/initializers/cors.rb
  db/seeds.rb
  spec/factories/game.rb
  spec/factories/user.rb
  spec/factories/user_game.rb
Labels: enhancement

#43 Bk/new function
  README.md
  app/graphql/mutations/create_user.rb
  app/graphql/mutations/create_user_game.rb
  app/graphql/mutations/delete_user_game.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/user_game_type.rb
  app/graphql/types/user_type.rb
  app/models/user_game.rb
  spec/graphql/mutations/create_user_game_spec.rb
  spec/graphql/mutations/delete_user_game_spec.rb
  spec/models/user_game_spec.rb
Labels: enhancement

#54 Bk/refactor delete mutations
  README.md
  app/graphql/mutations/delete_user.rb
  app/graphql/mutations/delete_user_game.rb
  app/graphql/mutations/update_user_game.rb
  app/graphql/mutations/user_games/destroy_user_game.rb
  app/graphql/mutations/users/create_user.rb
  app/graphql/types/query_type.rb
  app/graphql/types/user_game_type.rb
  app/graphql/types/user_type.rb
  db/migrate/20230211034810_add_status_to_user_games.rb
  spec/factories/user_game.rb
  spec/graphql/mutations/create_user_game_spec.rb
  spec/graphql/mutations/delete_user_game_spec.rb
  spec/graphql/mutations/delete_user_spec.rb
  spec/graphql/mutations/update_user_game_spec.rb
  spec/graphql/queries/users/get_user_spec.rb
Labels: bug

#58 Update README
  README.md
Labels: documentation

#61 Update README
  README.md
  app/graphql/mutations/update_user_game.rb
  spec/fixtures/vcr_cassettes/Types_QueryType/find_games/can_query_for_games_by_name.yml
  spec/graphql/mutations/update_user_game_spec.rb
  spec/graphql/queries/users/get_user_spec.rb
Labels: documentation
